name: release

on:
  push:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn clean package -P full
      - name: Get version
        id: version
        run: |
          echo "VERSION=$(cat pom.xml | grep -oPm1 '(?<=<revision>)[^<]+')" >> $GITHUB_OUTPUT
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          tag: ${{ steps.version.outputs.VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "packaging/target/*.zip,packaging/target/*.tgz,packaging/target/*.deb,packaging/target/*.rpm,tunnel-server/target/*fatjar.jar,bin/arthas.sh"

