name: release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn clean package -P full
      - name: Get POM version
        id: pom-version
        uses: CptMokoena/maven-get-version-action@1.0.3
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.pom-version.outputs.version }}
          tag: ${{ steps.pom-version.outputs.version }}
          files: |
            packaging/target/*.zip
            packaging/target/*.tgz
            packaging/target/*.deb
            packaging/target/*.rpm
            tunnel-server/target/*fatjar.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

